// desc.js — Model descriptions and fallback generator
const DESC = {
  // Llama
  "meta-llama/Llama-3.2-1B-Instruct":"Compact multilingual model for edge devices and on-device AI. Great for simple tasks with minimal resources.",
  "meta-llama/Llama-3.2-3B-Instruct":"Small but capable general-purpose model. Strong at summarization, instruction following, and basic reasoning.",
  "meta-llama/Llama-3.2-11B-Vision-Instruct":"Multimodal model that understands both text and images. Can describe photos, read documents, and answer visual questions.",
  "meta-llama/Llama-3.2-90B-Vision-Instruct":"Large multimodal model with strong vision and language capabilities. Handles complex visual reasoning tasks.",
  "meta-llama/Llama-3.1-8B-Instruct":"Versatile 8B model with 128K context. Strong at chat, coding, and general knowledge tasks.",
  "meta-llama/Llama-3.1-70B-Instruct":"High-performance open model rivaling GPT-4 class systems. Excellent at reasoning, coding, and multilingual tasks.",
  "meta-llama/Llama-3.1-405B-Instruct":"The largest open-weight model available. State-of-the-art performance across virtually all benchmarks.",
  "meta-llama/Llama-3.3-70B-Instruct":"Latest Llama 3 series with improved instruction following and reduced hallucinations over 3.1.",
  "meta-llama/Llama-4-Scout-17B-16E-Instruct":"Llama 4 MoE model with 16 experts. 10M token context window. Strong multimodal and multilingual capabilities.",
  "meta-llama/Llama-4-Maverick-17B-128E-Instruct":"Llama 4 flagship with 128 experts. Top-tier MoE performance for research and production workloads.",

  // CodeLlama
  "codellama/CodeLlama-7b-Instruct-hf":"Code-specialized Llama fine-tune. Supports code generation, completion, and debugging across many languages.",
  "codellama/CodeLlama-13b-Instruct-hf":"Mid-size code model with stronger reasoning than 7B. Good for complex code generation tasks.",
  "codellama/CodeLlama-34b-Instruct-hf":"Large code model excelling at code review, refactoring, and multi-file understanding.",
  "codellama/CodeLlama-70b-Instruct-hf":"The most capable CodeLlama. Near-GPT-4 level code generation with strong debugging skills.",

  // Mistral
  "mistralai/Mistral-7B-Instruct-v0.3":"Punches well above its weight class. One of the best 7B models for general chat and reasoning.",
  "mistralai/Mistral-Nemo-Instruct-2407":"12B model built with NVIDIA. 128K context with strong multilingual and coding performance.",
  "mistralai/Mistral-Small-Instruct-2409":"Mistral's optimized 22B model. Great balance of speed and capability for production use.",
  "mistralai/Mixtral-8x7B-Instruct-v0.1":"Sparse MoE model — only activates 12B params per token. Fast inference with 47B-level quality.",
  "mistralai/Mixtral-8x22B-Instruct-v0.1":"Large MoE with 39B active params. One of the strongest open MoE models for complex tasks.",
  "mistralai/Codestral-22B-v0.1":"Mistral's dedicated code model. Trained on 80+ languages with fill-in-the-middle support.",
  "mistralai/Pixtral-12B-2409":"Mistral's vision-language model. Understands images natively with strong text capabilities.",
  "mistralai/Mistral-Large-Instruct-2407":"Mistral's flagship 123B dense model. Top-tier reasoning and multilingual performance.",
  "mistralai/Mistral-Small-3.1-24B-Instruct-2503":"Latest Mistral Small with vision support. Fast, capable, and efficient for multimodal tasks.",
  "mistralai/Mistral-Small-4-119B-2603":"Mistral Small 4 — 119B MoE with only 6.5B active params. Multimodal, reasoning modes, 256K context. 3x faster than Small 3.",
  "mistralai/Pixtral-Large-Instruct-2411":"Large multimodal Mistral model. Strong at document understanding and visual reasoning.",
  "mistralai/Codestral-Mamba-7B-v0.1":"Code model using Mamba architecture instead of Transformer. Efficient for long code contexts.",
  "mistralai/Devstral-Small-2505":"Mistral's developer-focused model. Optimized for agentic coding tasks and tool use.",

  // Qwen 3
  "Qwen/Qwen3-0.6B":"Tiny but surprisingly capable. Runs on almost anything including phones and Raspberry Pi.",
  "Qwen/Qwen3-1.7B":"Compact model great for edge deployment. Supports both thinking and non-thinking modes.",
  "Qwen/Qwen3-4B":"Sweet spot for lightweight local AI. Strong multilingual support across 100+ languages.",
  "Qwen/Qwen3-8B":"Excellent general-purpose model. Competitive with much larger models on reasoning benchmarks.",
  "Qwen/Qwen3-14B":"Strong mid-range model for coding, math, and creative writing. Great performance per VRAM dollar.",
  "Qwen/Qwen3-30B-A3B":"MoE model activating only 3B params per token. Huge model quality at tiny inference cost.",
  "Qwen/Qwen3-32B":"One of the best open 32B models. Excellent at complex reasoning and long-form generation.",
  "Qwen/Qwen3-235B-A22B":"Massive MoE flagship. 22B active params deliver frontier-level performance on reasoning and code.",

  // Qwen 3.5
  "Qwen/Qwen3.5-0.8B":"Qwen 3.5 tiny model with native multimodal support. Hybrid GatedDeltaNet + attention architecture. 262K context.",
  "Qwen/Qwen3.5-2B":"Compact Qwen 3.5 with multimodal capabilities. Efficient for edge and mobile deployment. 262K context.",
  "Qwen/Qwen3.5-4B":"Small but powerful multimodal model. Supports text, image, and video input natively. 262K context.",
  "Qwen/Qwen3.5-9B":"Mid-range Qwen 3.5 with strong reasoning and multimodal understanding. 262K context, extendable to 1M.",
  "Qwen/Qwen3.5-27B":"Large dense Qwen 3.5. Excellent at coding, reasoning, and visual tasks. 262K context, extendable to 1M.",
  "Qwen/Qwen3.5-35B-A3B":"MoE model with 256 experts, only 3B active per token. Massive quality at tiny inference cost. 262K context.",
  "Qwen/Qwen3.5-122B-A10B":"Large MoE with 10B active params. Hybrid GatedDeltaNet + sparse MoE. Supports 201 languages. 262K context.",
  "Qwen/Qwen3.5-397B-A17B":"Qwen 3.5 flagship. 512 experts, 17B active. Frontier-level multimodal reasoning across text, image, and video.",

  // Qwen 2.5
  "Qwen/Qwen2.5-0.5B-Instruct":"Ultra-lightweight model for constrained environments. Basic chat and simple tasks.",
  "Qwen/Qwen2.5-1.5B-Instruct":"Small but effective for basic instruction following and text generation.",
  "Qwen/Qwen2.5-3B-Instruct":"Good entry-level model for local AI. Handles summarization and Q&A well.",
  "Qwen/Qwen2.5-7B-Instruct":"Solid all-rounder. Strong at coding, math, and multilingual tasks for its size.",
  "Qwen/Qwen2.5-14B-Instruct":"Excellent mid-range model. Competitive with Llama 3.1 70B on several benchmarks.",
  "Qwen/Qwen2.5-32B-Instruct":"High-capability model for demanding tasks. Strong reasoning and long-context understanding.",
  "Qwen/Qwen2.5-72B-Instruct":"Qwen's large flagship. Top-tier open model for complex reasoning, coding, and analysis.",
  "Qwen/Qwen3-Coder-30B-A3B-Instruct":"30B MoE code model with only 3B active params. Fast agentic coding with tool use. 262K context.",
  "Qwen/Qwen3-Coder-480B-A35B-Instruct":"480B MoE flagship coder. 35B active params, 160 experts. Rivals Claude Sonnet on coding. 262K context, extendable to 1M.",
  "Qwen/Qwen3-Coder-Next":"80B dense code model. Strong repo-scale code understanding and agentic workflows.",
  "Qwen/Qwen2.5-Coder-0.5B-Instruct":"Tiny code assistant for autocomplete and simple generation. Runs anywhere.",
  "Qwen/Qwen2.5-Coder-1.5B-Instruct":"Lightweight code model. Good for real-time code completion in IDEs.",
  "Qwen/Qwen2.5-Coder-3B-Instruct":"Capable small code model. Handles multi-file edits and debugging.",
  "Qwen/Qwen2.5-Coder-7B-Instruct":"Strong code model supporting 90+ languages. Great for local Copilot replacement.",
  "Qwen/Qwen2.5-Coder-14B-Instruct":"Powerful code model rivaling GPT-4 on coding benchmarks. Excellent for complex refactoring.",
  "Qwen/Qwen2.5-Coder-32B-Instruct":"One of the best open code models. Near-frontier performance on code generation and review.",
  "Qwen/QwQ-32B":"Qwen's reasoning specialist. Uses chain-of-thought to solve math, logic, and science problems.",

  // Qwen VL
  "Qwen/Qwen2-VL-7B-Instruct":"Vision-language model understanding images, charts, and documents. Good for OCR and visual Q&A.",
  "Qwen/Qwen2-VL-72B-Instruct":"Large vision-language model with state-of-the-art visual understanding capabilities.",
  "Qwen/Qwen2.5-VL-3B-Instruct":"Compact multimodal model. Understands images and video with minimal hardware.",
  "Qwen/Qwen2.5-VL-7B-Instruct":"Updated vision-language model with improved document and chart understanding.",
  "Qwen/Qwen2.5-VL-32B-Instruct":"Strong multimodal model for detailed image analysis and visual reasoning.",
  "Qwen/Qwen2.5-VL-72B-Instruct":"Flagship Qwen vision model. Excellent at complex visual tasks and long video understanding.",
  "Qwen/Qwen2-Audio-7B-Instruct":"Understands speech and audio. Can transcribe, translate, and answer questions about audio content.",
  "Qwen/Qwen2.5-Omni-7B":"Multimodal model handling text, images, audio, and video in a single model.",
  "Qwen/Qwen-Image-2512":"Top-ranked open-source text-to-image model. Enhanced human realism, natural detail, and text rendering.",
  "Qwen/Qwen-Image-Edit-2511":"Image editing model with character consistency, multi-person editing, built-in LoRA, and industrial design support.",

  // DeepSeek
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B":"Distilled reasoning model. Brings R1's chain-of-thought ability to a tiny package.",
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B":"7B reasoning model distilled from DeepSeek R1. Strong math and logic performance.",
  "deepseek-ai/DeepSeek-R1-Distill-Llama-8B":"R1 reasoning distilled into Llama 8B. Good balance of speed and reasoning quality.",
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B":"14B reasoning specialist. Excellent at step-by-step problem solving and analysis.",
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B":"Powerful reasoning model. Approaches full R1 quality on math and coding tasks.",
  "deepseek-ai/DeepSeek-R1-Distill-Llama-70B":"Large reasoning model with near-frontier performance on complex problem solving.",
  "deepseek-ai/DeepSeek-R1":"Full DeepSeek R1 with 671B MoE. One of the strongest reasoning models ever released as open-weight.",
  "deepseek-ai/DeepSeek-V3":"DeepSeek's flagship general model. 671B MoE with strong performance across all tasks.",
  "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct":"Lightweight MoE code model. Only 2.4B active params but strong coding performance.",
  "deepseek-ai/DeepSeek-Coder-V2-Instruct":"Large MoE code model. Exceptional at code generation, debugging, and repository-level tasks.",
  "deepseek-ai/DeepSeek-V2.5":"Unified chat and code model. Combines V2's capabilities with improved instruction following.",

  // Google Gemma
  "google/gemma-3-1b-it":"Google's tiny open model. Efficient and well-trained for basic tasks on minimal hardware.",
  "google/gemma-3-4b-it":"Compact multimodal model with vision support. Strong efficiency for its size class.",
  "google/gemma-3-12b-it":"Mid-range Gemma with vision. Excellent quality-to-size ratio from Google's training infrastructure.",
  "google/gemma-3-27b-it":"Gemma's largest model. Strong multimodal capabilities competitive with much bigger models.",
  "google/gemma-2-9b-it":"Previous-gen 9B model. Still very competitive for general chat and instruction following.",
  "google/gemma-2-27b-it":"Previous-gen large Gemma. Reliable for production workloads requiring good general performance.",
  "google/gemma-3n-e4b-it":"Gemma optimized for on-device deployment. Designed for mobile and edge inference.",

  // Microsoft Phi
  "microsoft/phi-4":"Microsoft's 14B model punching way above its weight. Excellent at reasoning, math, and coding.",
  "microsoft/Phi-4-mini-instruct":"Compact 3.8B model with surprisingly strong capabilities. Great for resource-constrained setups.",
  "microsoft/Phi-3.5-mini-instruct":"Previous-gen small Phi. Still excellent for lightweight local deployment.",
  "microsoft/Orca-2-7b":"Trained to use multiple reasoning strategies. Good at step-by-step analysis and explanation.",
  "microsoft/Phi-4-reasoning-plus":"Phi-4 fine-tuned specifically for complex reasoning tasks. Strong on math and logic puzzles.",
  "microsoft/Phi-4-multimodal-instruct":"Phi-4 with vision and speech input. Compact multimodal AI for edge devices.",
  "microsoft/Phi-3-medium-4k-instruct":"14B Phi-3 model. Strong general performance in a mid-range package.",
  "microsoft/Phi-3-vision-128k-instruct":"Vision-enabled Phi-3. Can understand images with a 128K context window.",

  // Cohere
  "CohereForAI/c4ai-command-r-v01":"Built for RAG and tool use. Excellent at grounded generation with source citations.",
  "CohereForAI/c4ai-command-r-plus-08-2024":"Cohere's large model. Top-tier for enterprise RAG, search, and agentic workflows.",
  "CohereForAI/c4ai-command-a-03-2025":"Latest Cohere MoE model. Strong at multilingual tasks with 23 language support.",

  // GLM / Zhipu
  "zai-org/GLM-5":"Frontier 744B MoE with 40B active params. DeepSeek Sparse Attention. Top-tier reasoning, coding, and agentic capabilities.",
  "THUDM/glm-4-9b-chat":"Chinese-English bilingual model with strong general capabilities. 1M token context support.",
  "THUDM/glm-4v-9b":"GLM with vision support. Understands Chinese and English text in images.",
  "THUDM/GLM-Z1-9B-0414":"GLM reasoning model using deep thinking. Strong at math, logic, and code.",
  "THUDM/GLM-Z1-32B-0414":"Large GLM reasoning model. Competitive with frontier reasoning models on complex tasks.",
  "THUDM/codegeex-4-all-9b":"Zhipu's code model. Multi-language code generation with IDE integration support.",
  "THUDM/GLM-4-9B-Chat-1M":"GLM-4 with 1 million token context window. Ideal for processing very long documents.",

  // Kimi / Moonshot
  "moonshotai/Kimi-K2.5":"Frontier 1T MoE model with 32B active params. 384 experts, 256K context. Excels at reasoning, coding, and multimodal tasks.",
  "moonshotai/Kimi-VL-A3B-Instruct":"Lightweight MoE vision-language model. Only 2.8B active params with strong visual understanding.",
  "moonshotai/Kimi-VL-A3B-Thinking":"Kimi VL with extended reasoning. Chain-of-thought over visual and text inputs.",

  // InternLM
  "internlm/internlm2_5-7b-chat":"Strong Chinese-English model from Shanghai AI Lab. Good at math, code, and chat.",
  "internlm/internlm2_5-20b-chat":"Larger InternLM with improved reasoning and knowledge capabilities.",
  "internlm/internlm3-8b-instruct":"Latest InternLM generation. Improved instruction following and reduced hallucinations.",

  // InternVL
  "OpenGVLab/InternVL2-2B":"Tiny vision-language model. Basic image understanding on minimal hardware.",
  "OpenGVLab/InternVL2-8B":"Capable vision model. Strong at OCR, chart reading, and visual Q&A.",
  "OpenGVLab/InternVL2-26B":"Large vision model with detailed image understanding and multi-image reasoning.",
  "OpenGVLab/InternVL2-40B":"High-performance multimodal model competitive with proprietary vision APIs.",
  "OpenGVLab/InternVL3-8B":"Latest InternVL with improved visual reasoning and document understanding.",
  "OpenGVLab/InternVL3-14B":"Strong mid-size vision model. Excellent at detailed image analysis.",

  // NVIDIA
  "nvidia/Llama-3_1-Nemotron-Ultra-253B-v1-FP8":"253B dense model derived from Llama 405B via NAS. Strong reasoning, code, and math. Configurable thinking mode. 128K context.",
  "nvidia/Nemotron-Cascade-2-30B-A3B":"30B MoE with only 3B active params. IMO 2025 gold medal. IOI 2025 gold. Exceptional math and competitive programming. Built on Nano 30B.",
  "nvidia/NVIDIA-Nemotron-3-Nano-4B-Instruct":"Tiny 4B model for edge and mobile. Fast inference on modest hardware.",
  "nvidia/NVIDIA-Nemotron-Nano-9B-v2":"9B general model. Strong instruction following for its size.",
  "nvidia/NVIDIA-Nemotron-Nano-12B-v2-BF16":"12B model with optional vision support. Good balance of speed and capability.",
  "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-Instruct":"30B MoE base with 3B active params. Efficient inference with large model quality.",
  "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16":"120B LatentMoE with 12B active. Hybrid Mamba-2 + MoE + Attention. 1M context. Strong agentic, coding, and reasoning.",
  "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF":"NVIDIA-optimized Llama 3.1. Improved helpfulness and accuracy via RLHF.",

  // IBM
  "ibm-granite/granite-3.1-2b-instruct":"IBM's enterprise-focused small model. Designed for business document processing.",
  "ibm-granite/granite-3.1-8b-instruct":"IBM's mid-size enterprise model. Strong at structured data and business tasks.",

  // BigCode
  "bigcode/starcoder2-3b":"Open-source code model trained on The Stack v2. Supports 600+ languages.",
  "bigcode/starcoder2-7b":"Mid-size StarCoder. Good for code completion and generation across many languages.",
  "bigcode/starcoder2-15b":"Largest StarCoder2. Strong code generation competitive with much larger models.",

  // Embedding models
  "sentence-transformers/all-MiniLM-L6-v2":"Fast, lightweight embedding model. Industry standard for semantic search and similarity.",
  "sentence-transformers/all-MiniLM-L12-v2":"Slightly larger MiniLM with better accuracy. Good speed-quality tradeoff for embeddings.",
  "BAAI/bge-small-en-v1.5":"Small but accurate English embedding model from Beijing Academy of AI.",
  "BAAI/bge-base-en-v1.5":"Base-size BGE embedding. Strong retrieval performance for its size.",
  "BAAI/bge-large-en-v1.5":"Large BGE embedding. Top-tier retrieval accuracy among sub-1B models.",
  "BAAI/bge-m3":"Multilingual embedding model supporting 100+ languages. Handles up to 8K tokens.",
  "nomic-ai/nomic-embed-text-v1.5":"Open-source embedding with 8K context. Strong at long document retrieval.",
  "mixedbread-ai/mxbai-embed-large-v1":"High-quality embeddings competitive with OpenAI's text-embedding-3-small.",
  "Alibaba-NLP/gte-Qwen2-1.5B-instruct":"Qwen-based embedding model. Excellent multilingual retrieval performance.",
  "Alibaba-NLP/gte-Qwen2-7B-instruct":"Large embedding model with state-of-the-art retrieval on MTEB benchmarks.",
  "jinaai/jina-embeddings-v3":"Jina's latest embeddings. Strong at code, multilingual, and long-context retrieval.",
  "Snowflake/snowflake-arctic-embed-m-v2.0":"Snowflake's mid-size embedding. Optimized for enterprise search and RAG.",
  "Snowflake/snowflake-arctic-embed-l-v2.0":"Large Snowflake embedding. Top retrieval accuracy for its size.",
  "intfloat/e5-mistral-7b-instruct":"7B embedding model based on Mistral. Very high accuracy at the cost of more compute.",
  "dunzhang/stella_en_1.5B_v5":"Efficient English embedding model. Strong performance on retrieval benchmarks.",

  // Vision models
  "vikhyatk/moondream2":"Ultra-compact vision model. Runs on edge devices, answers questions about images.",
  "llava-hf/llava-1.5-7b-hf":"Pioneering open vision-language model. Connects a vision encoder to Llama for image chat.",
  "llava-hf/llava-1.5-13b-hf":"Larger LLaVA with improved visual understanding and more detailed responses.",
  "openbmb/MiniCPM-V-2_6":"Efficient multimodal model from Tsinghua. Strong OCR and document understanding.",

  // Reasoning
  "NovaSky-Berkeley/Sky-T1-32B-Preview":"Berkeley's reasoning model. Trained with process reward models for better step-by-step logic.",
  "AIDC-AI/Marco-o1":"Open reasoning model focused on math and chain-of-thought problem solving.",
  "AIDC-AI/Marco-o1-CoT":"Marco-o1 with explicit chain-of-thought. Shows reasoning steps for transparency.",
  "Skywork/Skywork-o1-Open-Llama-3.1-8B":"Open reasoning model based on Llama 3.1. Good at math and logic puzzles.",

  // Community
  "teknium/OpenHermes-2.5-Mistral-7B":"Community fine-tune known for excellent instruction following. One of the most popular 7B models.",
  "HuggingFaceTB/SmolLM2-1.7B-Instruct":"HuggingFace's small language model. Designed for on-device and embedded AI.",
  "HuggingFaceTB/SmolLM2-135M-Instruct":"Ultra-tiny model for the most constrained devices. Basic text capabilities.",
  "HuggingFaceTB/SmolLM2-360M-Instruct":"Very small model that still handles simple instructions and text generation.",
  "tiiuae/falcon-40b-instruct":"TII's large open model. Trained on massive web data with strong general knowledge.",
  "databricks/dbrx-instruct":"Databricks' MoE model. 36B active params with strong code and general performance.",
  "NousResearch/Hermes-3-Llama-3.1-8B":"Nous Research fine-tune with excellent function calling and structured output.",
  "NousResearch/Hermes-3-Llama-3.1-70B":"Large Hermes model. Top-tier for agentic tasks, tool use, and structured generation.",
  "01-ai/Yi-1.5-9B-Chat":"Chinese AI startup's mid-size model. Strong bilingual (Chinese/English) capabilities.",
  "01-ai/Yi-1.5-34B-Chat":"Yi's large model. Competitive bilingual performance with strong reasoning.",
  "01-ai/Yi-34B-Chat":"Original Yi 34B. Still a strong bilingual model for Chinese/English tasks.",
  "upstage/SOLAR-10.7B-Instruct-v1.0":"Depth-upscaled Llama model. Unique architecture that punches above its size class.",
  "allenai/OLMo-2-1124-7B-Instruct":"Fully open model from AI2 — open data, code, weights, and training details.",
  "allenai/OLMo-2-1124-13B-Instruct":"Larger OLMo with improved performance. Fully transparent and reproducible.",
  "TinyLlama/TinyLlama-1.1B-Chat-v1.0":"Trained on 3T tokens despite being 1.1B. Surprisingly capable for its tiny size.",
  "stabilityai/stablelm-2-1_6b-chat":"Stability AI's compact model. Efficient and well-suited for basic local AI tasks.",
  "stabilityai/stablelm-2-12b-chat":"Mid-size StableLM. Good general performance in a resource-friendly package.",
  "HuggingFaceH4/zephyr-7b-beta":"DPO-aligned Mistral fine-tune. Known for helpful, harmless responses.",
  "cognitivecomputations/dolphin-2.9.3-llama-3.1-8B":"Uncensored Llama fine-tune. Follows all instructions without refusals.",
  "WizardLMTeam/WizardLM-2-8x22B":"Microsoft-backed fine-tune of Mixtral. Strong complex instruction following.",
  "Intel/neural-chat-7b-v3-3":"Intel-optimized chat model. Fine-tuned for helpful conversation with good latency.",
  "Nexusflow/Starling-LM-7B-beta":"RLAIF-trained model that ranks high on chat benchmarks despite being only 7B.",
  "Salesforce/xLAM-7b-r":"Salesforce's function-calling specialist. Built for AI agent and tool use tasks.",

  // AI21
  "ai21labs/AI21-Jamba-1.5-Mini":"Hybrid Mamba-Transformer architecture. 256K context with very efficient inference.",
  "ai21labs/AI21-Jamba-1.5-Large":"Large Jamba model. Massive context with fast inference thanks to Mamba layers.",

  // RWKV
  "RWKV/v6-Finch-1B6-HF":"Linear attention model — runs like an RNN. Constant memory usage regardless of context length.",
  "RWKV/v6-Finch-3B-HF":"RWKV-6 with improved training. Efficient inference with no quadratic attention overhead.",
  "RWKV/v6-Finch-7B-HF":"Mid-size RWKV. Great for long-context tasks where Transformer VRAM usage would explode.",
  "RWKV/v6-Finch-14B-HF":"Largest RWKV-6. Competitive quality with Transformers at a fraction of the inference cost.",

  // ===== IMAGE GENERATION =====
  "stabilityai/stable-diffusion-xl-base-1.0":"Industry standard for image generation. Produces high-quality 1024x1024 images with huge community support.",
  "stabilityai/stable-diffusion-3-medium-diffusers":"SD3 with MMDiT architecture. Better text rendering and composition than SDXL.",
  "stabilityai/stable-diffusion-3.5-medium":"Updated SD3 with improved quality and faster generation. Good speed-quality balance.",
  "stabilityai/stable-diffusion-3.5-large":"High-quality SD3.5. Better coherence and detail than medium at the cost of more VRAM.",
  "stabilityai/stable-diffusion-3.5-large-turbo":"Distilled SD3.5 Large for faster generation. Near-equal quality in fewer steps.",
  "black-forest-labs/FLUX.1-dev":"State-of-the-art image generation from Black Forest Labs. Exceptional quality and prompt adherence.",
  "black-forest-labs/FLUX.1-schnell":"Fast version of FLUX.1. Generates in 1-4 steps with impressive quality for the speed.",
  "black-forest-labs/FLUX.1-Fill-dev":"FLUX.1 for inpainting and outpainting. Seamlessly edits parts of existing images.",
  "black-forest-labs/FLUX.1-Redux-dev":"FLUX.1 for image variations. Generates similar images based on a reference input.",
  "Kwai-Kolors/Kolors":"Kuaishou's image model. Strong at photorealistic images and Chinese text understanding.",
  "PixArt-alpha/PixArt-XL-2-1024-MS":"Efficient DiT-based image generator. High quality at a fraction of SDXL's compute cost.",
  "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS":"Updated PixArt with improved quality and 4K resolution support.",
  "playgroundai/playground-v2.5-1024px-aesthetic":"Optimized for aesthetic quality. Produces visually striking images with strong composition.",
  "Tencent-Hunyuan/HunyuanDiT-v1.2-Diffusers":"Tencent's bilingual image model. Understands prompts in both English and Chinese.",
  "OnomaAIResearch/Illustrious-xl-early-release-v0":"Anime and illustration specialist SDXL model. Excels at character art and stylized imagery.",
  "kandinsky-community/kandinsky-3":"Sber's image model. Strong artistic style with good prompt understanding.",
  "dataautogpt3/FLUX-AestheticAnime":"FLUX fine-tuned for anime art. High-quality anime and illustration generation.",
  "Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro":"FLUX with ControlNet support. Generate images guided by depth maps, edges, or poses.",
  "InstantX/FLUX.1-dev-IP-Adapter":"FLUX with IP-Adapter. Generate images matching the style or content of a reference image.",
  "ByteDance/SDXL-Lightning":"ByteDance's distilled SDXL. Generates quality images in just 1-4 steps.",
  "latent-consistency/lcm-sdxl":"Latent Consistency Model for SDXL. Near-instant image generation in 2-4 steps.",
  "SG161222/RealVisXL_V4.0":"Photorealistic SDXL fine-tune. Excels at generating realistic photos and portraits.",
  "Lykon/dreamshaper-xl-v2-turbo":"Versatile SDXL fine-tune. Great at both realistic and artistic styles with fast generation.",
  "RunDiffusion/Juggernaut-XL-v9":"Popular SDXL fine-tune known for exceptional photorealism and detail.",
  "stabilityai/sdxl-turbo":"Official SDXL distillation. Real-time image generation in a single step.",
  "stabilityai/stable-cascade":"Two-stage image model working in a highly compressed latent space. Very VRAM efficient.",

  // ===== VIDEO GENERATION =====
  "THUDM/CogVideoX-2b":"Compact text-to-video model. Generates short video clips from text descriptions.",
  "THUDM/CogVideoX-5b":"Larger CogVideo with improved motion and consistency in generated videos.",
  "THUDM/CogVideoX1.5-5B":"Updated CogVideo with longer generation and better temporal coherence.",
  "Wan-AI/Wan2.1-T2V-1.3B":"Alibaba's compact text-to-video model. Generates video from text on modest hardware.",
  "Wan-AI/Wan2.1-T2V-14B":"Large Wan model producing high-quality videos with complex motion and scene changes.",
  "Wan-AI/Wan2.1-I2V-14B-480P":"Image-to-video model. Animates still images into 480p video clips.",
  "Wan-AI/Wan2.1-I2V-14B-720P":"Higher resolution image-to-video. Produces 720p animated videos from reference images.",
  "tencent/HunyuanVideo":"Tencent's large video model. High-quality generation with strong motion and scene understanding.",
  "genmo/mochi-1-preview":"Genmo's video generation model. Known for realistic motion and physical consistency.",
  "Lightricks/LTX-Video":"Fast video generation model. Produces short clips efficiently with good visual quality.",
  "Lightricks/LTX-2":"19B DiT audio-video foundation model. Generates synchronized video and audio in one model. Text/image/audio to video.",
  "Lightricks/LTX-2.3":"21B upgrade to LTX-2. Improved audio-visual quality and prompt adherence. Supports 4-20 step generation.",
  "stabilityai/stable-video-diffusion-img2vid-xt-1-1":"Stability's image-to-video model. Animates images into short video sequences.",
  "rhymes-ai/Allegro":"Text-to-video model with strong prompt adherence and motion quality.",
  "Doubiiu/ToonCrafter":"Generates animated sequences between keyframes. Great for cartoon and animation workflows.",
  "guoyww/AnimateDiff":"Motion module that adds animation to any Stable Diffusion image model.",
  "hpcai-tech/Open-Sora":"Open-source Sora-like video generation. Community-driven text-to-video model.",
  "Pyramid-Flow/pyramid-flow-miniflux":"Efficient video generation using pyramidal flow matching. Fast inference.",

  // ===== AUDIO =====
  "openai/whisper-large-v3":"Best open speech-to-text model. Supports 99 languages with near-human accuracy.",
  "openai/whisper-large-v3-turbo":"Faster Whisper with slightly reduced accuracy. Great for real-time transcription.",
  "openai/whisper-medium":"Mid-size Whisper. Good accuracy-speed balance for most transcription needs.",
  "openai/whisper-small":"Lightweight Whisper for faster-than-realtime transcription on modest hardware.",
  "openai/whisper-base":"Minimal Whisper model. Basic transcription for very constrained environments.",
  "suno/bark":"Text-to-speech with voice cloning, music, and sound effects. Very expressive and natural.",
  "coqui/XTTS-v2":"Multi-language TTS with voice cloning from a 6-second sample. 17 languages supported.",
  "fishaudio/fish-speech-1.5":"Fast TTS with voice cloning. Low latency suitable for real-time applications.",
  "fishaudio/s2-pro":"5B Dual-AR TTS model. 80+ languages, inline prosody/emotion control with 15K+ tags. Sub-100ms time-to-first-audio.",
  "nari-labs/Dia-1.6B":"Dialogue TTS that generates natural conversations with multiple speakers and emotions.",
  "parler-tts/parler-tts-large-v1":"Describe the voice you want in text and it generates speech matching that description.",
  "OuteAI/OuteTTS-0.3-1B":"Lightweight TTS model. Fast speech generation with decent quality on minimal resources.",
  "facebook/musicgen-medium":"Meta's music generation model. Creates music from text descriptions or melodies.",
  "facebook/musicgen-large":"Larger MusicGen with higher quality and more complex musical compositions.",
  "stabilityai/stable-audio-open-1.0":"Stability's audio generation. Creates music and sound effects from text prompts.",

  // New models
  "xai-org/grok-1":"xAI's first open-weight model. 314B MoE (86B active params). Raw base weights — no instruction tuning. A beast to run locally.",
  "LGAI-EXAONE/EXAONE-4.0-32B":"LG AI Research's flagship open model. Strong multilingual performance especially in Korean and English.",
  "LGAI-EXAONE/EXAONE-Deep-32B":"EXAONE fine-tuned for deep reasoning. Competitive with much larger models on math and logic.",
  "LGAI-EXAONE/EXAONE-Deep-2.4B":"Compact reasoning model from LG AI. Surprisingly strong reasoning for its tiny size.",
  "MiniMaxAI/MiniMax-M2.1":"229B dense model. Excels at coding, tool use, and agentic tasks. Outperforms Claude Sonnet 4.5 in multilingual coding.",
  "MiniMaxAI/MiniMax-M2.5":"229B upgrade to M2.1. 80% on SWE-Bench Verified. Full-stack coding, agentic tool use, and office automation. 37% faster than M2.1.",
  "baichuan-inc/Baichuan4-Turbo":"Major Chinese LLM optimized for domain-specific tasks — medical, legal, finance. Strong bilingual capabilities.",
  "CohereLabs/aya-23-35B":"Leading open multilingual model supporting 23 languages. Built for non-English AI use cases.",
  "CohereLabs/aya-23-8B":"Compact multilingual model. Good quality across 23 languages on modest hardware.",
  "moonshotai/Kimi-Dev-72B":"Moonshot's coding and agentic model. Built for software development workflows and tool use.",
  "infly/OpenCoder-8B-Instruct":"Fully open code model — open data, training, and weights. Transparent and reproducible.",
  "allenai/Molmo-72B-0924":"AI2's large vision-language model. Fully open with state-of-the-art visual understanding.",
  "allenai/Molmo-7B-D-0924":"Mid-size Molmo. Strong image understanding with fully open weights and training data.",
  "allenai/Molmo-1B-D-0924":"Tiny Molmo for edge devices. Basic vision-language capabilities at minimal cost.",
  "llava-hf/llava-onevision-qwen2-72b-ov-hf":"Unified vision model handling images, multi-image, and video. Top-tier open VLM.",
  "llava-hf/llava-onevision-qwen2-7b-ov-hf":"Compact LLaVA OneVision. Strong multimodal understanding on consumer hardware.",
  "HuggingFaceTB/SmolVLM-2.2B-Instruct":"Tiny vision-language model from HuggingFace. Runs on phones and edge devices.",
  "HuggingFaceM4/Idefics3-8B-Llama3":"HuggingFace's open VLM. Strong document understanding and visual Q&A.",
  "google/medgemma-4b-it":"Google's medical AI model. Understands medical images and clinical text. For research use.",
  "google/medgemma-27b-text-it":"Large medical text model from Google. Strong at clinical reasoning and medical Q&A.",
  "BioMistral/BioMistral-7B":"Mistral fine-tuned on biomedical literature. Good for medical and life science tasks.",
  "aaditya/Llama3-OpenBioLLM-70B":"Large biomedical model. Fine-tuned on medical datasets for clinical and research use.",
  "epfl-llm/meditron-70b":"EPFL's medical LLM trained on clinical guidelines and medical literature. Research-grade.",
  "black-forest-labs/FLUX.1-Kontext-dev":"FLUX for image editing. Edit specific parts of images with text instructions.",
  "HiDream-ai/HiDream-I1-Full":"New image generator rivaling FLUX. Strong prompt adherence and photorealism.",
  "HiDream-ai/HiDream-I1-Dev":"HiDream developer variant. Same quality with faster iteration.",
  "Alpha-VLLM/Lumina-Image-2.0":"Efficient DiT image generator. High quality at very low compute cost.",
  "Wan-AI/Wan2.2-T2V-5B":"Updated Wan text-to-video. Improved motion quality and longer generation.",
  "lllyasviel/FramePack":"Viral video generation tool. Generates video from images with minimal VRAM via frame packing.",
  "microsoft/TRELLIS-2-4B":"Microsoft's 3D generation model. Creates 3D assets from text or images.",
  "tencent/Hunyuan3D-2":"Tencent's 3D model generation. Creates textured 3D meshes from images.",
  "hexgrad/Kokoro-82M":"Ultra-lightweight TTS. Natural-sounding speech from a tiny 82M parameter model.",
  "sesame/csm-1b":"Conversational speech model. Generates natural dialogue with emotional expression.",
  "resemble-ai/chatterbox-turbo":"Fast TTS with voice cloning from a 15-second sample. Zero-shot voice synthesis.",
  "canopylabs/orpheus-3b-0.1-ft":"Expressive TTS model. Generates speech with laughter, emotion, and natural prosody.",
  "SWivid/F5-TTS":"Fast voice cloning TTS. Clone any voice from a short sample with high fidelity.",
  "SparkAudio/Spark-TTS-0.5B":"Lightweight voice cloning TTS. Fast inference suitable for real-time applications.",
  "FunAudioLLM/CosyVoice2-0.5B":"Alibaba's voice cloning TTS. Supports multiple languages with natural prosody.",
  "ChatTTS/ChatTTS":"Conversational TTS optimized for dialogue. Generates natural-sounding chat responses.",
  "kyutai/moshi-7b":"First real-time full-duplex speech-to-speech model. Talk to it like a phone call.",
  "nvidia/parakeet-tdt-0.6b-v2":"NVIDIA's speech recognition model. Beats Whisper on several ASR benchmarks.",
  "nvidia/canary-qwen-2.5b":"NVIDIA's multilingual ASR. Strong transcription across multiple languages.",
  "ace-step/ACE-Step-v1.5":"Music generation model. Creates full songs from text descriptions of genre, mood, and style.",
  "m-a-p/YuE-s1-7B-anneal-en-cot":"Lyrics-to-song model. Generates complete songs with vocals from lyrics input.",
  "nomic-ai/modernbert-embed-base":"Modern BERT architecture for embeddings. Fast and efficient for search and RAG.",
  "nomic-ai/nomic-embed-text-v2-moe":"MoE embedding model. High accuracy with efficient inference via sparse activation.",
  "johnsnowlabs/JSL-MedLlama-3-8B-v2.0":"Medical LLM from John Snow Labs. Fine-tuned for clinical NLP, diagnosis support, and medical Q&A.",
  "AdaptLLM/medicine-chat":"Llama adapted for medical conversations. Trained on medical literature for healthcare Q&A.",
  "TheFinAI/finma-7b-full":"Finance-specialized LLM. Trained on financial datasets for analysis, sentiment, and report generation.",
  "AdaptLLM/finance-chat":"Llama adapted for finance. Trained on financial news, SEC filings, and market analysis.",
  "ai4finance/FinGPT-Llama2-7B":"Open-source financial LLM. Built for stock analysis, sentiment detection, and financial reasoning.",
  "SALT-NLP/InvestLM_65B":"Large investment-focused model. Trained for portfolio analysis, market reasoning, and financial advice.",
  "equall/Saul-7B-Instruct-v1":"Legal domain LLM. Fine-tuned on legal texts for contract analysis, case research, and legal Q&A.",
};

// Fallback description generator for models not in the lookup
function getDesc(m) {
  if (DESC[m.id]) return DESC[m.id];
  const catDescs = {
    general: "General-purpose language model for chat, reasoning, and text generation.",
    code: "Code-specialized model for generation, completion, and debugging.",
    reason: "Reasoning-focused model optimized for math, logic, and step-by-step problem solving.",
    vision: "Vision-language model that understands both images and text.",
    medical: "Medical/biomedical model for clinical reasoning, diagnosis support, and healthcare Q&A. Not FDA-approved — for research use only.",
    finance: "Finance-specialized model for market analysis, financial reasoning, and report generation. Not financial advice.",
    legal: "Legal domain model for contract analysis, case research, and legal Q&A. Not a substitute for professional legal counsel.",
    embed: "Embedding model for semantic search, retrieval, and similarity matching.",
    image: "Image generation model for creating visuals from text prompts.",
    video: "Video generation model for creating video clips from text or images.",
    threeD: "3D generation model for creating 3D assets, meshes, and objects from text or images.",
    audio: "Audio model for speech, music, or sound processing and generation.",
  };
  return `${m.f} ${m.p} parameter ${catDescs[m.c] || catDescs.general}`;
}
